version: "2"

services:
  hive:
    image: apache/hive:3.1.3
    container_name: hive
    environment:
      - HIVE_ROOT=/opt/hive
      - SERVICE_NAME=hiveserver2
    ports:
      - 10002:10002
      - 10000:10000
      - 9083:9083
    networks:
      - big_data_network

  spark:
    image: bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_NO_DAEMONIZE=yes
    ports:
      - "8080:8080"
      - "4040:4040"
    networks:
      - big_data_network
    depends_on:
      - hive

  spark-worker:
    image: bitnami/spark:3.5
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    depends_on:
      - spark
    networks:
      - big_data_network

networks:
  big_data_network:
    external: true
