version: "2"

services:
  spark-driver:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - big_data_network
    volumes:
      - .:/pop

networks:
  big_data_network:
    external: true
